const data=[
    {
        "id": "1",
       "name":"Taipei",
       "namepicture":"./picture/1.jpeg",
       "link":"https://english.gov.taipei/",
       "lat":"25.0777561",
       "lng":"121.4992963",
       "address":"No.1, City Hall Rd., Xinyi District, Taipei City, Taiwan (R.O.C.)",
       "diarytitle":"Diary 1",
       "diaryquestion":"Introduce your favorite city from your personal perspective (historical traces, development in recent years, population, your favorite place(s), unique feature, suggestion for improvement, wishes for the future, ...)",
       "diary":"My favorite city is on an island, where is located in Asia. The island surrounded by the Pacific Ocean and it has lots of mountains on the island. The name  Formosa dates from 1542 when Portuguese sailors sighted an uncharted island and noted it on their maps as Ilha Formosa (beautiful island). The island be occupied by Spanish and Holland, Japan for several years, so you can see the different foreign buildings in the city. Spanish occupy north of Taiwan, Which is Taipei and Keelung. Holland occupy south of Taiwan, which is Tainan and Kaohsiung. The answer to this question is Taiwan, and Taiwan face political problems for decades year, suffer from different kinds of pressure from China. China thinks Taiwan is part of them but actually we have our own government, solider, law, we just speak the same language, that’s all. Taiwan now population is around 23 million. A hundred years ago, the people living in Taiwan were separated into aboriginal and Pingpu groups. Pinpu live in-ground and aboriginal live in the mountain, they have serious fights really often. But now, we are peaceful and make good friends with each other, it doesn't have any suspicion between each other. and there are 16 different groups of Aboriginals in Taiwan. But now all of them already assimilated into people living on the ground. Of course, they do live in the mountain as well, that's their home and very beautiful and fascinating if you have a chance to visit them, the culture, living way, language, foods. Taipei city in Taiwan develop rapidly decade years ago including the fields of technology, social media, industry, etc, and also has the highest building called 101 building, which has 101 floors, it used to be the highest building in the world. My favorite place in the city is the exhibition, museum, mountain, riverside, and the old street hidden in the city, I like to explore the place make me relax and enjoy the vibe of the city. The best thing is that you can see the landscape of the ocean and mountains at the same time, it’s an advantage when you live on the island. Because of the limit of the island, so it’s really hard to make a physical improvement for citizens feeling it, but we can based on the digital content or policy to make people feel like living here is convenient and comfortable. The big thing I think the city needs to change is the advertisement, you can see so many advertisements in each store, it makes the street look really messy and dirty….",
       "picture":{
            "picture1":"./picture/1-1.jpeg",
            "picture1detail":"Period of Netherlands times",
            "picture2":"./picture/1-2.jpeg",
            "picture2detail":"Taipei 101",
            "picture3":"./picture/1-3.jpeg",
            "picture3detail":"Taipei street",
       }
    },
    {
        "id": "2",
       "name":"Schloss Sanssouci",
       "namepicture":"./picture/2.jpeg",
       "link":"https://www.spsg.de/schloesser-gaerten/objekt/schloss-sanssouci/",
       "lat":"52.402687",
       "lng":"13.038551",
       "address":"Lennéstraße 32A, 14469 Potsdam",
       "diarytitle":"Diary 2",
       "diaryquestion":"What does World Heritage mean (in comparison to National Heritage)? Are there UNESCO World Heritage sites in your city/in your country? Which positive/negative effects does it have on the city?",
       "diary":"Nowadays, each country can easily get to the other countries and get the news from the internet immediately, It’s no border between each other, internet is anywhere. The world heritage represents the different culture or the special story behind it, it means that all the people who live on the earth can understand the history and the events in each country by the heritage. People is not only care about their own’s culture and stories also concerned about the events/activities in the world.Unfortunately, there are no UNESCO world heritage sites in my country(Taiwan). Because of the political problem, we are not admitted to being a country by the world. Of course, we have lots of national heritage in Taiwan including national parks, aboriginal living places (There are 16 different aboriginal groups in Taiwan), etc. The first one is Yushan National Park, located in the center of Taiwan, and the Yushan mountain is the highest mountain in Taiwan(3600m), and it snows at the top in the winter sometimes. On the other hand, we usually called him the protection of god mountain because the mountain always can destroy the structure of a typhoon, which is one of the natural disasters. The mountain totally decrease the damage by typhoon. The second one is Taroko National Park. Taroko National Park is located in Hualien, Taichung, and Nantou cities, there are many incredible natural wonders such as cliffs and canyons. When you self-driving through the east part of Taiwan, you can enjoy the ocean and mountains on both sides. The third one is Penghu Basalt Nature Reserve. Penghu is the only island in Taiwan that is composed of basalt. Subsequently, due to the influence of sea erosion and other topographical effects, many undulating and varied columnar basalts were formed. And it is the unique scene you can see on the island. The positive effect of this heritage is that Taiwan can be noticed in the world and also understand the history of Taiwan. it’s quite a huge effect for us. And the negative effect is that as an island too rely on tourism to get the benefits, we should more focus on developing the business/ digital technologies by ourselves.",
       "picture":{
            "picture1":"./picture/2-1.jpeg",
            "picture1detail":"Yushan National Park",
            "picture2":"./picture/2-2.jpeg",
            "picture2detail":"Taroko National Park",
            "picture3":"./picture/2-3.jpeg",
            "picture3detail":"Penghu Basalt Nature Reserve",
       }
    },
    {
        "id": "3",
       "name":"Haus der Wannseekonferenz",
       "namepicture":"./picture/3.jpeg",
       "link":"https://www.ghwk.de/en/",
       "lat":"52.4329193",
       "lng":"13.1632673",
       "address":"Am Großen Wannsee 56-58, 14109 Berlin",
       "diarytitle":"Diary 3",
       "diaryquestion":"The artist Gunnar Demnig remembers the victims of National Socialism by installing commemorative brass plaques in the pavement in front of their last address of choice. In German those commemorative brass plaques are called Stolpersteine (lit. stumbling stones).For further information check http://www.stolpersteine.eu/en/home/Are there stumbling stones in your city? Are there other ways of remembering victims installed in your city? What do you think about these ways of remembrance?Look for a stumbling stone in your neighborhood and do some research on the person.",
       "diary":"In Taiwan, we don’t have this kind of “stolpersteine” everywhere. We only have a statue located at the entrance of the memory park or museum. But I do like the way Germany did. It makes you more closely and knows the event happening at the moment. If you only visit the museum and memory park, maybe you only understand the history but you can’t feel the emotion from the victim. Because that is the place where happens really unbelievable things. In my opinion, another way to memorize the victim is that you can put it in the school homework and develop a interactive map for student exploring the city. And also put some special events on the map, then student could correspond the event to the “Stolpersteine”. Why is “stolpersteine” and statue so important? It’s because that is the key reason cause our city development so far, admit the mistake and based on the mistake to make the country more peaceful and not make it once again. On the other hand, it lets citizens know the history and emotion when they pass by the place.In berlin, I live in Kreuzberg, and there is a “stolpersteine” just located around my place. Georg Kotte was the son of a master woodturner from Altenburg in Thuringia and began an apprenticeship as a publishing clerk in 1903. After he was released from French captivity in mid-1920, he joined the “Werden” volunteer corps. In 1921 he returned to his hometown. From then on he worked in the local editorial department of the Altenburger Zeitung and also made a name for himself as a reporter for court hearings, concerts and theater performances. It is not known why he was released from the Scherl-Verlag in the spring of 1937. A time of poverty began for him in which he had to get by on a weekly unemployment benefit of RM 5.34. On October 14, 1938, Georg Kotte was arrested at around 10 p.m. at the Brandenburg Gate near the Reichstag. His attempt to escape failed. While being beaten, he was taken to the Gestapo prison at Prinz-Albrecht-Strasse 8, where the abuse continued for days. On August 27, 1943, Georg Kotte was released and at the same time brought to the Berlin police. She had applied for “preventive detention” and had him deported to the Buchenwald concentration camp, where he died on January 30, 1944. Another story I found is really famous, called Anne Frank. She was a German-Dutch girl of Jewish origin who was born in 1934 Emigrated to the Netherlands with his parents and sister Margot to avoid persecution by the National Socialists and fell victim to the National Socialist Holocaust shortly before the end of the war. In the Netherlands, Anne Frank lived with her family in a hidden secret annexe in Amsterdam from July 1942. In this hiding place she recorded her experiences and thoughts in a diary, which was published after the war as the diary of Anne Frank by her father Otto Frank.The diary is considered a historical document from the time of the Holocaust and the author is a symbol against the inhumanity of genocide during the Nazi era.",
       "picture":{
            "picture1":"./picture/3-1.jpg",
            "picture1detail":"Stumbling stones near to my place",
            "picture2":"./picture/3-2.jpg",
            "picture2detail":"Wall of Anna",
            "picture3":"./picture/3-3.jpg",
            "picture3detail":"Anna's diary",
       }
    },
    {
        "id": "4",
       "name":"Lindenstraße memorial",
       "namepicture":"./picture/4.jpeg",
       "link":"https://www.gedenkstaette-lindenstrasse.de/en/",
       "lat":"52.4043389",
       "lng":"13.0574978",
       "address":"Lindenstraße 54, 14467 Potsdam",
       "diarytitle":"Diary 4",
       "diaryquestion":"Do you notice the former German division in your everyday life in Potsdam/Berlin? If so, how?Are/were there any visible and/or invisible boundaries in your city/country?",
       "diary":"Today we visited the Lindenstraße memorial in Potsdam. The guide shows us the place that gains insights into the detention and interrogation practices employed by the Soviet secret police (NKWD/MGB). It is a wonderful experience for me. Although we have taught European history about the second war or something it is too broad. And now I’m in Germany, I can know the detail of each story and the real scene the victim suffered, the clothes they wore, the food they eat, the place they lived, and also the truck they are being transferred. It’s so amazing and really unbelievable that the government did the things. There is a place I saw the German division in Berlin, called Charlie check point. It became the most famous crossing point between East and West Germany. On 22 September 1961, Allied guards began registering members of the American, British and French forces before trips to East Berlin and foreign tourists could find out about their stay there. Once the checkpoint was designated a crossing point for members of the Allied armed forces, a month later in October 1961 it became the scene of a tank confrontation. American and Soviet tanks took up position and faced each other with weapons primed. The second place I noticed in the Berlin is the Berlin wall and it is famous all over the world. Berlin wall was a guarded concrete barrier that physically and ideologically divided Berlin from 1961 to 1989. Construction of the wall was commenced by the German Democratic Republic (GDR, East Germany) on 13 August 1961. The Wall cut off West Berlin from surrounding East Germany, including East Berlin. The barrier included guard towers placed along large concrete walls, accompanied by a wide area (later known as the death strip) that contained anti-vehicle trenches, beds of nails and other defenses. The Eastern Bloc portrayed the Wall as protecting its population from fascist elements conspiring to prevent the will of the people from building a socialist state in East Germany. In my country, Taiwan itself is a boundary because Taiwan is an island. As you can see the country located in the Pacific Ocean are democracy country, so it’s kind of invisible boundaries against the communism from China.",
       "picture":{
            "picture1":"./picture/4-1.jpeg",
            "picture1detail":"Inside of memorial",
            "picture2":"./picture/4-2.jpeg",
            "picture2detail":"Charlie checkpoint",
            "picture3":"./picture/4-3.jpg",
            "picture3detail":"Border of west/east berlin",
       }
    },
    {
        "id": "5",
       "name":"Neues Potsdamer Toleranzedikt e.V.",
       "namepicture":"./picture/5.jpeg",
       "link":"https://www.potsdamer-toleranzedikt.de/",
       "lat":"52.402891",
       "lng":"13.0633667",
       "address":"Gutenbergstraße 62, 14467 Potsdam",
       "diarytitle":"Diary 5",
       "diaryquestion":"How does diversity become visible in a city?Think about/inform yourself about migration history in your city. Where is diversity visible in your city?",
       "diary":"In my opinion, diversity in the city could be separated into architecture, culture. And it would be discovered obviously if the country was occupied by another country for a while. not only the food would be affected also the culture, living way, religion, and so on. the war does not only bring the nightmare out and also something interesting finding and inspired different thinking.In Taiwan, we have been through dutch, Spain, japan took over Taiwan for a while. In the aspect of architecture, we can see the castle from dutch and Spain in North Taiwan and South Taiwan, and especially the president hall was built by the Japanese, and then we still use it as our president hall, even time flies, and we re-decorate the building again but the spirit always still there. In the language aspect, I think the biggest effect was Japanese because we were taken over by Japan before the second war, and japan regard Taiwan as a supplement station when they attack east-south Asia countries. So lots of Japanese solider and people were lived in Taiwan, they also built transfer stations and industries in Taiwan, pushing Taiwan not to rely on agriculture anymore. So people start to accept Japanese education in Taiwan, cause a lot of our grandmothers can only speak Japanese, that was changed a lot for us. even the elderly people who come from Japan missed their home in Taiwan and special to visit Taiwan for looking for the house they lived in before.",
       "picture":{
            "picture1":"./picture/5-1.jpeg",
            "picture1detail":"President hall of Taiwan",
            "picture2":"./picture/5-2.jpeg",
            "picture2detail":"School in period of Japan",
            "picture3":"./picture/5-3.jpeg",
            "picture3detail":"Taipei Tech(period of Japan)",
       }
    },
    {
        "id": "6",
       "name":"Garnisonkirche Potsdam",
       "namepicture":"./picture/6.jpeg",
       "link":"https://garnisonkirche-potsdam.de/en/",
       "lat":"52.3963324",
       "lng":"13.053834",
       "address":"Breite Str. 7, 14467 Potsdam",
       "diarytitle":"Diary 6",
       "diaryquestion":"Are there similar discussions on urban development like Garnisonkirche/ Rechenzentrum going on in your city?Which buildings are preserved? Which buildings were rebuilt/reconstructed? Which buildings were demolished? Why? Who decided on this?",
       "diary":"There is an area in Taipei, Taiwan, which was regarded as a historical building. and now are becoming workspaces for artists to hold an exhibition or rent working spaces, called Treasure Hill Artist Village.In this area, it was built by Taiwanese for living space. Since Japan took over Taiwan, the Japanese make this area became military location because the location was near the Keelung river and stand on the hillside. the Japanese also built several underground bunkers and garrison quarters for ammunition storage. In 1960 years, the Taiwan government thinks this area was illegal and too old, it's not suitable for the building beside them, so they plan to demolish it. but the citizen jump out to protest them to protect their benefits, even though the government still demolished several buildings, the people were still not afraid to keep protesting it. in the end, the construction of demolishing stopped by government and become one of the urban development plans in the future. After that, not only the department of urban planning at Taiwan university do interviews and investigations to support them become an area for the artist also the organization of the urban revolution got the case from the government to practice urban space reform. In 2004, Treasure Rock was officially registered as a historical building, and it has been preserved in the form of settlement activation. At present, there are 14 artist studios in Treasure Rock Art Village, which serve as the working and living space for domestic and foreign artists in the village. In addition, rehearsal rooms, exhibition rooms, and outdoor performance spaces are also planned.",
       "picture":{
            "picture1":"./picture/6-1.jpeg",
            "picture1detail":"Treasure Hill Artist Village",
            "picture2":"./picture/6-2.jpeg",
            "picture2detail":"Environment of Trasure hill",
            "picture3":"./picture/6-3.jpeg",
            "picture3detail":"Inside of the building",
       }
    },
    {
        "id": "7",
       "name":"Christmas Avenue Berlin",
       "namepicture":"./picture/7.jpeg",
       "link":"http://christmas-avenue.berlin/",
       "lat":"52.4990783",
       "lng":"13.3505534",
       "address":"Nollendorfpl., 10777 Berlin",
       "diarytitle":"Diary 7",
       "diaryquestion":"Which holidays are celebrated in your city? How is the city changing for festivities? What can you hear, smell and taste during festivities?",
       "diary":"Officially we have several festivals that we will celebrate with family, in order is Chinese new year, Dragon Boat Festival, Ching Ming Festival, moon Festival. There are three or fours days of vacation for the family to go traveling or stay at home.During the Chinese new year, usually happens at the end of January, and the symbol of the Chinese new year is gathering together, enjoying the food, doing the firework, playing Mahjong, which is a kind of game for everyone. and we can get a red envelope from elderly, which is put the money in the envelope., it's really excited for children to get money. but most parents will take over the money and say that we will help you to save the money in case you need to use it in the future. During the dragon boat festival, the family will go to the supermarket to buy rice dumplings or prepare the material by themselves, it really depends. the reason we eat this at the festival is that memorize a person called Qu Yuan. the story was too long and too hard to explain because it's come from several hundred years ago. he suicides with the stone in the river. After that, the fisherman took out the rice balls, eggs, and other food prepared for Qu Yuan and threw them into the river. He thought that if the fish, lobster, and crab were full, they would not bite Qu Yuan's body. When people saw it, they followed suit. During the Ching Ming festival, all the people will back home to pray for the worship ancestor. It's a huge and serious festival for Taiwanese, and then we just drink and eat together after that. During the Moon Festival, we will go BBQ at home, doing the firework, you can smell the BBQ in every street. It's a nice festival for people chatting, singing, dancing, playing together. Even some family will do the BBQ all the vacation, super crazy!",
       "picture":{
            "picture1":"./picture/7-1.jpeg",
            "picture1detail":"Red envelope(Spring festival)",
            "picture2":"./picture/7-2.jpeg",
            "picture2detail":"Rice dumplings(dragon boat festival)",
            "picture3":"./picture/7-3.jpeg",
            "picture3detail":"Worship ancestor(Ching Ming festival)",
       }
    },
    {
        "id": "8",
       "name":"Schiffbauergasse",
       "namepicture":"./picture/8.jpeg",
       "link":"https://schiffbauergasse.de/",
       "lat":"52.4046586",
       "lng":"13.0720643",
       "address":"Schiffbauergasse 17, 14467 Potsdam",
       "diarytitle":"Diary 8",
       "diaryquestion":"How are former industrial sites in your city used today?",
       "diary":"There are two places were built as industrial sites in Taiwan, one is Songshan cultural park, the another is Huashan 1914 Creative Park. Songshan was built by the period of Japan. It used to be an industrial site for Cigarette, it sold lots of Cigarette for the Japanese solider who were fight for second war in the south-east Asia country. After the end of the war, Taiwan government take the Taiwan back again, and keep introducing the cigarette as well, but the urban development going on the progress, the competition of cigarette decrease a lot cause the industry stop producing. And know the area is becoming the cultural environment, exhibition area, and also for people held any activities here. The area still keep the architecture and building standing on the area. What is now Huashan 1914 Creative Park opened in 1914 as Taihoku Winery during Japanese rule. It was privately owned winery that produced sake and ginseng wines, and bred moth orchids. In 1922, the government included wine within a list of monopoly items. They bought the winery and changed the name to Taiwan Governor-General's Monopoly Bureau, Taihoku Wine Factory. The winery then produced rice wine and liquors. After second war, Huashan begin to produce the Camphor to get more profit, but the world has changed a lot cause the camphor cant be sold out anymore, so the government decided to dissolve the place in 1956. And the sound of public group ask government to open this place for public are getting higher, so huashan end the business of camphor. In 2003, the Council for Cultural Affairs (CCA) took over its management. They planned a complete reconstruction that started in early 2004. And the end of 2005, Huashan 1914 Creative Park opened and offered artists a place to develop their creations and non-profit organizations a venue to hold activities. In 2007, the CCA signed a contract with Taiwan Cultural-Creative Development Co., Ltd. to run the park. Since then, theater groups, painters, wood sculptors, writers, movie producers and directors from Taiwan and abroad have found in the park a timeless pace to showcase their creative talents. So now, there are lots of international exhibition coming to Taiwan and become a casual place for Taipei citizens. You can see so many people and tourism here to relax or camping here.",
       "picture":{
            "picture1":"./picture/8-1.jpeg",
            "picture1detail":"Songshan cultural park",
            "picture2":"./picture/8-2.jpeg",
            "picture2detail":"department of Songshan",
            "picture3":"./picture/8-3.jpeg",
            "picture3detail":"Huashan 1914 Creative Park",
       }
    },
    {
        "id": "9",
       "name":"Möckernkiez 16",
       "namepicture":"./picture/9.jpeg",
       "link":"",
       "lat":"52.4928508",
       "lng":"13.3772068",
       "address":"Möckernkiez 16, Berlin",
       "diarytitle":"Diary 9",
       "diaryquestion":"Concluding reflection of the course based on your expectations and knowledge/insights acquired",
       "diary":"To be honest, this is my first time in Europe. I am very excited, especially Germany is full of history. At the beginning of the semester, professor Constanze invites me to join the course to unfold Potsdam, it’s a great chance for me to explore the city with a group of professional people. The course is very interesting, impressive, especially the story about the Nazi and second war because we are not really deep dive into German history when I had in the school before, so I am so excited that many details and stories were disclosed by the staff. Exploring the city is an important issue for foreigners, you have to know how is the situation changing so far, What kind of policy and strategy they pursue in order to make the city better, you can’t ignore the city development, this is also the reason for citizens life become better. ",
       "picture":{
            "picture1":"./picture/9-1.jpg",
            "picture1detail":"FH;P campus",
            "picture2":"./picture/9-2.jpg",
            "picture2detail":"FH;P building D (Design department)",
            "picture3":"./picture/9-3.jpg",
            "picture3detail":"FH;P walking area",
       }
    },
    
]
export default data